### ISSUE TITLE
Install warning: 'deprecated nomnom@1.8.1: Package no longer supported'

### ISSUE THREAD

**Issue by yawaramin** [ruyadorno/snapstub#14]
Looks like https://www.npmjs.com/package/@gerhobbelt/nomnom is a drop-in replacement. Of course there are other options available.

**Comment by ruyadorno** [comment]
thanks for reporting it 😄 

updated all dependencies, should be fixed in [v3.0.0](https://github.com/ruyadorno/snapstub/releases/tag/v3.0.0)
