### ISSUE TITLE
trailing whitespaces inside empty objects and empty arrays

### ISSUE THREAD

**Issue by mmedeirosupgrade** [ruyadorno/snapstub#19]
right now if I run:

```sh
curl https://cdn.example.com/foo.json | snapstub save /foo
```

and the JSON response contains empty objects/arrays like:

```json
{ "foo": [], "bar": {} }
```

the saved file will be formatted like (note trailing whitespaces):

```json
{
    "foo": [
        
    ],
    "bar": {
        
    }
}
```

I would expect it to be formatted like this instead:

```json
{
  "foo": [],
  "bar": {}
}
```

Maybe we should use `JSON.stringify({ "foo": [], "bar": {} }, undefined, '   ')` instead of `jsonlint/lib/formatter`? - one advantage is that `jsonlint` is [able to format invalid/broken JSON as well](https://github.com/zaach/jsonlint/blob/843cad2bbd87139bb75806c1c24fe0d821a41ff4/lib/formatter.js#L10) tho...

**Comment by ruyadorno** [comment]
the reason for using **jsonlint** is in order to actually have a well-formatted json file (including nested level indenting, etc) so with that reasoning just replacing it for `JSON.stringify` is not really an option 🤔 

how does it affects the expected json response you're using? is it causing unexpected problems?

**Comment by mmedeirosupgrade** [comment]
> the reason for using jsonlint is in order to actually have a well-formatted json file (including nested level indenting, etc) so with that reasoning just replacing it for JSON.stringify is not really an option 

[third parameter of `JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Parameters) works for nested objects/arrays as well:

```js
JSON.stringify(
  { foo: [{ lorem: { ipsum: [1,2,3], dolor: { amet: 1 }} }], bar: {} },
  undefined,
 2
);
```

Outputs:

```json
{
  "foo": [
    {
      "lorem": {
        "ipsum": [
          1,
          2,
          3
        ],
        "dolor": {
          "amet": 1
        }
      }
    }
  ],
  "bar": {}
}
```

> how does it affects the expected json response you're using? is it causing unexpected problems?

on my specific case it added a bunch of unrelated changes to an existing mock file (which was generated manually)... but, some editors might have a setting to [remove trailing whitespaces during save](https://editorconfig.org/); some pre-commit hooks might be [checking for trailing whitespaces](https://stackoverflow.com/questions/591923/make-git-automatically-remove-trailing-whitespace-before-committing); etc...
