### ISSUE TITLE
Upgrading to stubborn-server@2

### ISSUE THREAD

**Issue by igneel64** [ruyadorno/snapstub#26]
Hey @ruyadorno, I have used this package with a really nice use-case that would require the CORS upgrade that we added in zeachco/stubborn-server#54.
 
Would it be in your plans to allow a PR with the upgrade? As I have seen from the release notes the only breaking change is requirment of Node >= 10.

**Comment by ruyadorno** [comment]
sure thing 👍

**Comment by ruyadorno** [comment]
Thanks @igneel64 🎉 

`v5.0.0` is out! Sorry for the delay 😬
