### ISSUE TITLE
Mechanism to add endpoints from secure hosts that do not contain a valid certificate

### ISSUE THREAD

**Issue by zeachco** [ruyadorno/snapstub#3]
Unfortunatly, some dev environment are less flexible than others and dev stacks are run on ssl port only.

example : `snapstub add https://localhost`

the work around is to call `export NODE_TLS_REJECT_UNAUTHORIZED="0"` before stubing but it's a bit insecure for all command that follows as it affect all processes started from the same cli and child nodes as well

my suggestion is to add a flag to *snapstub* to configure in it's process only with `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` just before the request call to scope that security issue only within the mock tool

What do you think?
maybe it should be implemented into stubborn-server instead?

otherwise it's not blocking anything
![image](https://cloud.githubusercontent.com/assets/1691052/22601373/992ae2fc-ea0c-11e6-9829-4b9faad0d236.png)

**Comment by ruyadorno** [comment]
I think the idea is valid but the `add` command doesn't really have much to do with `stubborn-server` other than placing the files at the expected location, so I think the ball is def in `snapstub`'s court.

A flag for that would be handy but to be honest, it's such an edge case that I think just documenting the usage of `export NODE_TLS_REJECT_UNAUTHORIZED="0"` should be fine, of course we should mention the [security implications](https://github.com/nodejs/node/issues/5258) but `add` is quite a simple command that will only execute that request and terminates right away.

**Comment by zeachco** [comment]
Sounds good

**Comment by ruyadorno** [comment]
close for inactivity
